### PR TITLE
Guzzle 7

### PR DESCRIPTION
**Pull request by ajohnson6494**
This PR updates the library to allow for guzzle7 which is now required for Laravel version 8.

### CODE REVIEW

**Comment by joecampo** [comment]
Hey thanks for the PR!

Question: Why did you move the json decode out of the base ShipStation class and only onto the Endpoint class? So then only calls to ->shipments or ->orders will get decoded responses, while everything else will get the un-decoded Guzzle response. I don't think we should introduce that behavior.

**Comment by ajohnson6494** [comment]
Hey @joecampo,

Thanks for the quick response, the reason that I moved it into the endpoint class, is because returning json for the get, post, etc. methods would not be compatible with the parent Client class.

If we are going to extend the GuzzleHttp\Client class, then you have to return a response object and not the json decoded body. 

Would it make more since to change the ShipStation class not extend the GuzzleHttp\Client, but rather have a private property that was the GuzzleHttp\Client? Then we could keep the ShipStation get, post, etc. methods the same and return json?

**Comment by joecampo** [comment]
Ah that makes sense, yeah it makes more sense to just resolve it. Probably should have never extended it, but I can't remember what I was thinking that long ago 😅

**Comment by joecampo** [comment]
This is much better, thanks!

**Pull request merged**
